# This is the name of your app on Fly.io. It needs to be unique.
app = 'smartcardlink-app'
# The primary region for your application.
primary_region = 'jnb'
[build]
# This block configures the service your app provides.
[[services]]
  # This is the internal port your application listens on.
  internal_port = 5000
  protocol = "tcp"
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "GET"
    # Corrective action: Change the path to a public endpoint for health checks.
    path = "/"
    protocol = "http"
    timeout = "2s"
[env]
  # Environment variables for your application go here.
  # For example:
  # DB_HOST = "your-database-host"